// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZAIipC7THXYt6NqaCl_aw3vZZE-iGxhk',
    appId: '1:292234202902:web:f09aff1261331f66d04a37',
    messagingSenderId: '292234202902',
    projectId: 'sabe7-45121',
    authDomain: 'sabe7-45121.firebaseapp.com',
    storageBucket: 'sabe7-45121.firebasestorage.app',
    measurementId: 'G-83ZK1W9J8W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4YtetftelHftwo6XkZ_9vccv2Tod1q4w',
    appId: '1:292234202902:android:8d6952684f17f300d04a37',
    messagingSenderId: '292234202902',
    projectId: 'sabe7-45121',
    storageBucket: 'sabe7-45121.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIWe8KvAS-Xqwh03RwpUgDFGAGYEnver4',
    appId: '1:292234202902:ios:130736efe662c871d04a37',
    messagingSenderId: '292234202902',
    projectId: 'sabe7-45121',
    storageBucket: 'sabe7-45121.firebasestorage.app',
    iosBundleId: 'com.sabeh.sabehDashboardApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIWe8KvAS-Xqwh03RwpUgDFGAGYEnver4',
    appId: '1:292234202902:ios:130736efe662c871d04a37',
    messagingSenderId: '292234202902',
    projectId: 'sabe7-45121',
    storageBucket: 'sabe7-45121.firebasestorage.app',
    iosBundleId: 'com.sabeh.sabehDashboardApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZAIipC7THXYt6NqaCl_aw3vZZE-iGxhk',
    appId: '1:292234202902:web:968c49289549bf34d04a37',
    messagingSenderId: '292234202902',
    projectId: 'sabe7-45121',
    authDomain: 'sabe7-45121.firebaseapp.com',
    storageBucket: 'sabe7-45121.firebasestorage.app',
    measurementId: 'G-56PEXFL7CK',
  );
}
